### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jtamerius** [Quantipy/quantipy3#10]
I followed the instructions for installing but it fails every time. I was able to get all dependencies loaded and can import the Quantipy3 library, but there doesn't seem to be any methods associated with it. Just an empty module. Any help would be much appreciated! I am working on Windows 10.

**Comment by geirfreysson** [comment]
What exact directory are you in when you import? Can you share what script/commands you've entered and what happens?

We're going to provide quantipy3 with pip asap so this will be solved when that happens!

**Comment by jtamerius** [comment]
Hey Geir!

Here is the script:

conda create -n envqp python=3

git clone https://github.com/Quantipy/quantipy3.git  #this puts the folder in my working directory (not envqp)

conda activate envqp
pip install -r quantipy3/requirements.txt   ###I get a bunch of errors with this line, so I installed manually using a combination of conda and pip

Then I go into Python I run:

Import Quantipy3 as qp

It loads fine, but it doesn't recognize any qp commands.



Thanks for your help in advance! When do you think the API will be ready?Thanks,
James


James Tamerius
Senior Research Analyst
Research and Analysis
858-633-7913 office
520-780-7650 mobile

Center for Sustainable Energy(r)
3980 Sherman Street, Suite 170
San Diego, CA 92110


Learn more about our mission to decarbonize at EnergyCenter.org<https://energycenter.org/?utm_source=CSE&utm_medium=email&utm_campaign=signature>

**Comment by geirfreysson** [comment]
Hi James.

The problem is that even though this repo is called quantipy3, the package is still called quantipy. You also need to import it from the repo path.

```
cd quantipy3
import quantipy as qp
```

One way of doing it is to add this at the top of your script

```
sys.path.append('/path/to/your/directory/quantipy3/')
import quantipy as qp
```

This will of course finally be solved when we add support for installing via `pip`.

**Comment by jttaggart** [comment]
I have the same problem. Just can't get to install package. Was able to install all the supporting using requirements.txt

**Comment by geirfreysson** [comment]
@jttaggart, what directory are you in when you import the library? You need to import 'quantipy', not quantipy3. 

Did you try [my previous answer](https://github.com/Quantipy/quantipy3/issues/10#issuecomment-596454632) in this thread?

**Comment by jttaggart** [comment]
Hello,

 

I’m using Pycharm. I was able to manually with pip3 install -r requrirenets.txt and they all seemed to be present when I ckecked in Pycharm.

 

I think this is what I should have to import

 

import sys
sys.path.append('C:/Downloads/quantipy3/quantipy')
import quantipy as qp

 

Regards,

 

John

**Comment by jtamerius** [comment]
> Hi James.
> 
> The problem is that even though this repo is called quantipy3, the package is still called quantipy. You also need to import it from the repo path.
> 
> ```
> cd quantipy3
> import quantipy as qp
> ```
> 
> One way of doing it is to add this at the top of your script
> 
> ```
> sys.path.append('/path/to/your/directory/quantipy3/')
> import quantipy as qp
> ```


This worked for me...thanks!!!
