### ISSUE TITLE
Reading CSV

### ISSUE THREAD

**Issue by KushagraPan** [Quantipy/quantipy3#19]
Hey, I have survey data recorded in a CSV(via google sheets) file, don't have a metadata(json) file for the same.
How to go about finding weights using Quantipy?

**Comment by geirfreysson** [comment]
Hi there.

You can use the from_components method in a dataset. You read it into a dataframe with pandas and then pass the dataframe into from_components.

```
import quantipy as qp
import pandas as pd

dataframe = pd.read_csv('yourfile.csv')

dataset = qp.dataset('my dataset')
dataset.from_components(dataframe)
```

In a perfect world, this would be included in the library, like dataset.read_csv(csvfile) and if you want to be a hero, you can add a pull request ⚡
