### ISSUE TITLE
Error while installing quantipy

### ISSUE THREAD

**Issue by jgdpsingh** [Quantipy/quantipy3#22]
@geirfreysson @Kushagrapan
I am having this error while installing quantipy in python 2.7 environment.. kindly help

ERROR: Could not find a version that satisfies the requirement ftfy==5.5.1 (from quantipy==0.2.1->-r requirements_dev.txt (line 4)) (from versions: 1.0, 2.0, 2.0.1, 2.0.2, 3.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.3.0, 3.4.0, 4.0.0, 4.1.0, 4.1.1, 4.2.0, 4.3.1, 4.4, 4.4.1, 4.4.2, 4.4.3, 5.0, 5.0.1, 5.0.2, 5.1, 5.1.1, 5.2.0, 5.3.0)
ERROR: No matching distribution found for ftfy==5.5.1 (from quantipy==0.2.1->-r requirements_dev.txt (line 4))

**Comment by geirfreysson** [comment]
Hi @jgdpsingh.

You need to raise this issue in the [quantipy](https://github.com/Quantipy/quantipy) repository (not this one, quantipy3) as that is the repo with the python2 version of Quantipy.

Have you tried installing the pip requirements for that repo?

**Comment by jgdpsingh** [comment]
Will try that too.. thanks @geirfreysson .. will raise the issue in quantipy repository next time if something turns up.
