### ISSUE TITLE
new crosstab() function doesn't show significance if arg ci='%c'

### ISSUE THREAD

**Issue by tc423** [Quantipy/quantipy3#33]
First of all, fantastic that crosstab() now allows adding of significance view. However, when we assign '%c' to the argument ci, specifying sig_level no longer gives us the sig view. Also, when ci='%c' and xtotal=True, shouldn't the base now be 100.0? Thank you!

**Comment by geirfreysson** [comment]
Ah yes, because the sig-testing relies on the counts it doesn't populate if you're only viewing the percentages. We need to add the counts to the calculations if the user has requested a sig-test but then remove it from the results.

**Comment by tc423** [comment]
I see, thank you! I was looking to create a very specific view, but this is helpful!

**Comment by geirfreysson** [comment]
We have a pull request that fixes the first part of this issue which will be merged soon (tomorrow probably) @tc423, but I think how the `xtotal` paramters works is logical. Another matter is to include that in the sigtest - currently the sigtest isn't run with that column included but we should be able to add it as the underlying engine allows it. But that is way down the line.

This is what `xtotal=True` looks like. Shows the pct distribution within the total group and the base at the top.

![Screen Shot 2021-03-22 at 18 01 27](https://user-images.githubusercontent.com/4630/112036589-b79ed000-8b38-11eb-9dfd-74f351592fe7.png)

**Comment by geirfreysson** [comment]
Implemented not showing the counts but still including them in the calculations for the sig tests.
