### ISSUE TITLE
data key ct: x: [___] not found. But column exists in both data and meta

### ISSUE THREAD

**Issue by tc423** [Quantipy/quantipy3#43]
Hi I would love to understand how I can resolve this issue - I have inspected both the data object and the meta object, and the column in question does exist in both, when when using ds.crosstab(), quantipy throws an error saying the data key is not found. Thank you!
![image](https://user-images.githubusercontent.com/8795591/119078068-0d540380-ba28-11eb-9def-72f10e876eed.png)

**Comment by geirfreysson** [comment]
Could you provide a little bit more detail?

The code you are running and the full error report?

**Comment by tc423** [comment]
I think this was an issue because `E10` was a recoded column, I was able to resolve this by creating the column and saving to a .csv file before calling that file into a DataSet object. Weirdly this doesn't happen with another recoded column

**Comment by geirfreysson** [comment]
If you could add some information on how the column was created, we can try and replicate this and fix it. If not, we can also close the issue.
